### PR TITLE
Add colors to slices/git_status

### PR DESCRIPTION
**Pull request by nagromc**
This patch will set colors in the git status slice as follows:

Screenshot

### CODE REVIEW

**Comment by kamontat** [comment]
Can you help me? 
I can't get git_status  correctly, do you know why?
screen shot 2560-05-03 at 11 27 57 pm

**Comment by nagromc** [comment]
You are in a Git repo, right?

Can you provide more information to understand the problem?

**Comment by japrogramer** [comment]
hmm, is there a simpler way to place color highlights on a per slice bases? say a user defined method. 
like for example
```
    let g:promptline_preset = {
            \'a'     : [ ${wrap}32${end_wrap} promptline#slices#jobs(),
                       \ promptline#slices#python_virtualenv(),
                       \ '$USER' ],
            \'b'     : [ promptline#slices#cwd() ],
            \'c'     : [ promptline#slices#vcs_branch(),
                       \ promptline#slices#git_status(),
                       \ '${wrap}32${end_wrap} $(git rev-parse --short HEAD 2>/dev/null)'],
            \'warn'  : [ promptline#slices#last_exit_code() ],
            \'x'     : ['%*'],
            \'z'     : [ promptline#slices#host() ]}
```

**Comment by japrogramer** [comment]
oh it does work!

**Comment by japrogramer** [comment]
I would think that something like this would work and it does, except that the wrap doesn't actually change the color of the text as expected, Would expet this to work because it works with
${wrap}35${end_wrap}%*

```
\ '$(temp=$(git rev-parse --short HEAD 2>/dev/null) && [ ! -z '$temp' ]
   \  && echo \\\${wrap}32\\\${end_wrap}$temp; unset temp || echo )'
```

**Pull request closed without merging**
