### PR TITLE
add support for conda environments

### PR DESCRIPTION
**Pull request by stanleykylee**

### CODE REVIEW

**Comment by edkolev** [comment]
Thanks. Could you modify this so it's its own slice - conda isn't python specific as far as I can tell.

**Comment by stanleykylee** [comment]
done!

**Comment by edkolev** [comment]
Could you also update the README about the new slice, below this line
```
" promptline#slices#git_status() - count of commits ahead/behind upstream, count of modified/added/unmerged files, symbol for clean branch and symbol for existing untraced files
```

Please squash the commits.

**Comment by stanleykylee** [comment]
updated!

**Comment by edkolev** [comment]
Thanks, looks good!

Would you like to add your name to [this file](https://github.com/edkolev/promptline.vim/blob/master/CONTRIBUTORS.md)?

**Comment by stanleykylee** [comment]
sure thing, did you want me to make the change or you will?

**Comment by edkolev** [comment]
I wanted you to add it but it doesn't really matter :) You're in CONTRIBUTORS.md now, thanks! https://github.com/edkolev/promptline.vim/commit/bcce033792fb1d5745f42fe65b963754c5353847

**Pull request merged**
